# These are supported funding model platforms

patreon:  OrlovskyConsultingGbR
BTC: bc1qzfjtuxc6e68kzfaexr995xtu5xjtyzmtuukvz6
ETH: 0x89895850C2346EBE3a0d693be8c7d9a52A58f15E
Dogecoin: D9wLEo8t4pTVZ8Xw7buxe4Hkqp3HwFMnqR
Solana: BT15RhmCfzmB8s8FrAEN7awVYyt6ikfXMg4SrEceKRmD
VRSC: RBL7ia5LWdpgrArDu97JqDF15cg7WZ7xma
Bank holder: Alexander Orlovsky
IBAN: DE78370190001011197027
BIC: BUNQDE82
