#ATTENTION ! ATTENTION ! ATTENTION
#THIS IS NOT PRODUCTION READY VSFTPD CONFIG USE IT ONLY FOR TESTING OR TEMP PURPOSES!
# FINAL WARNING THIS NOT SECURE CONFIG!
background=NO
listen_port=21
#the case when you run vsftpd in your qemu
#Best practice configure ip your trust !
listen_address=0.0.0.0
listen=YES
#one of this must be enabled either you use ipv6 or ipv4
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
xferlog_std_format=YES
xferlog_file=/home/filehoster/logs/xferlog.log
vsftpd_log_file=/home/filehoster/logs/vsftpd.log
log_ftp_protocol=YES
connect_from_port_20=NO
chroot_local_user=YES
local_root=/mnt/t2-trunk/ftp/
secure_chroot_dir=/home/filehoster/ftp
pam_service_name=vsftpd
#rsa_cert_file=
#rsa_private_key_file=
ssl_enable= NO
ssl_tlsv1= NO
ssl_sslv2= NO
ssl_sslv3=NO
allow_anon_ssl=NO
force_local_data_ssl= NO
force_local_logins_ssl= NO
require_ssl_reuse=NO
#ssl_ciphers=HIGH
pasv_address=127.0.0.1
pasv_min_port=40000
pasv_max_port=50000
debug_ssl=NO
nopriv_user=filehoster
allow_writeable_chroot=YES
pasv_enable=YES
