# Redirect the non-standard /libexec to the T2-approved /usr/libexec
var_append confopt ' ' '--libexecdir=/usr/libexec'

# Optional: ensure it doesn't try to be too smart with path detection
var_append confopt ' ' '--bindir=/bin --sbindir=/sbin'
