rungpepinstall=0

pkg_scons_make() {
    gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2
}

pkg_install() {
    python3 -m installer --destdir="$root" .dist/*.whl
}

hook_add make    5 pkg_scons_make
hook_add install 5 pkg_install
